spring.application.name=joinUs


# MongoDB Client
mongodb.uri=mongodb://localhost:27017
mongodb.database=joinUs

#Neo4J Client
neo4j.uri=neo4j://127.0.0.1:7687
neo4j.username=neo4j
neo4j.password=Klajdi2003
neo4j.defaultDatabase=firstdb


